name: Release Existing SoulPeace PDFs

permissions:
  contents: write # Needed for softprops/action-gh-release to create releases
  # actions: write # May not be needed if only uploading artifacts from workspace

on:
  push:
    tags:
      - '*-v*.*.*'      # e.g. jp-v1.0.1, soulpeace_de_v1.00.pdf (matches this pattern indirectly if tag is like de-v1.0.0)
      - 'quick-v*.*.*'  # e.g. quick-v1.0.2
  workflow_dispatch: # Allows manual triggering

jobs:
  release-pdfs:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: (Diagnostic) List contents of the pdf directory
      # This helps confirm the files are where we expect them after checkout
      - name: List PDF directory contents
        run: |
          echo "Listing contents of pdf/ directory:"
          ls -la pdf/
        continue-on-error: true # Don't fail the job if ls fails (e.g., dir doesn't exist)

      # Step 3: Create a GitHub Release if triggered by a tag push
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2 # Use latest v2 release
        with:
          # Use the pattern that matches your files in the pdf directory
          files: pdf/*.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Upload PDFs as workflow artifact if manually triggered
      - name: Upload artifacts when manually triggered
        if: github.event_name == 'workflow_dispatch'
        # --- UPDATED ACTION VERSION ---
        uses: actions/upload-artifact@v4
        # --- END UPDATE ---
        with:
          name: existing-pdfs # Name of the artifact zip file
          # Use the pattern that matches your files in the pdf directory
          path: pdf/*.pdf
          if-no-files-found: warn # Good practice: warn instead of error if no files match