name: Release Existing SoulPeace PDFs

permissions:
  contents: write
  actions: write

on:
  push:
    tags:
      - '*-v*.*.*'      # e.g. jp-v1.0.1
      - 'quick-v*.*.*'  # e.g. quick-v1.0.2
  workflow_dispatch:

jobs:
  release-pdfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: List PDF directory contents
        run: ls -la pdf/

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            pdf/*.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts when manually triggered
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v3.1.3
        with:
          name: existing-pdfs
          path: pdf/*.pdf
          if-no-files-found: warn
