name: Release SoulPeace PDFs (Full Compilation)

permissions:
  contents: write # Needed for softprops/action-gh-release to create releases
  # actions: write # May not be needed if only uploading artifacts from workspace

on:
  push:
    tags:
      - 'v*.*.*'       # Run on tags like v1.0.0
      - 'full-v*.*.*'  # Run on tags like full-v1.0.0
  workflow_dispatch:    # Allow manual triggering for testing

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install system dependencies (fonts) needed by LaTeX
      - name: Install required fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends fonts-liberation fonts-noto fonts-noto-cjk
          # Added --no-install-recommends to potentially speed up install slightly

      # Step 3: Set up the TeX Live environment
      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3 # v3 is current for this action
        with:
          packages: > # Using YAML block scalar for readability
            scheme-basic
            fontspec
            geometry
            hyperref
            setspace
            parskip
            polyglossia
            xecjk
            noto
          # Consider adding any other specific packages your .tex files might need

      # Step 4: Compile the .tex source files into PDFs
      - name: Compile PDFs
        run: |
          mkdir -p soulpeace_pdf # Create output directory if it doesn't exist
          echo "Starting PDF compilation..."
          for file in soulpeace/*.tex; do
            echo "Compiling $file..."
            # Run twice to resolve references, TOCs, etc.
            xelatex -interaction=nonstopmode -output-directory=soulpeace_pdf "$file"
            xelatex -interaction=nonstopmode -output-directory=soulpeace_pdf "$file"
            # Check exit code? Add error handling? (Optional enhancement)
          done
          echo "Compilation loop finished."

      # Step 5: (Diagnostic) List the generated PDF files
      - name: List generated PDF files
        run: |
          echo "Listing contents of soulpeace_pdf/ directory:"
          ls -la soulpeace_pdf/
        # No continue-on-error here; if ls fails, something is wrong before release/upload

      # Step 6: Create a GitHub Release if triggered by a tag push
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2 # Use latest v2 release
        with:
          # Ensure this pattern matches the files generated in soulpeace_pdf/
          files: soulpeace_pdf/*.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 7: Upload compiled PDFs as workflow artifact if manually triggered
      - name: Upload artifacts when manually triggered
        if: github.event_name == 'workflow_dispatch'
        # --- UPDATED ACTION VERSION ---
        uses: actions/upload-artifact@v4
        # --- END UPDATE ---
        with:
          name: compiled-pdfs # Name of the artifact zip file
          # Ensure this path matches the directory where PDFs were compiled
          path: soulpeace_pdf/*.pdf
          if-no-files-found: warn # Changed from 'error' to 'warn' for consistency
                                  # If compilation fails, the job won't fail here,
                                  # making it easier to see compilation logs.